Update privacy.txt
uBlockOrigin/uAssets pull request #11160
Opened 2022-01-01 04:38 UTC by shenzhiming88

From AdGuard, this Cookie sets a unique user id for tracking how the user uses the site.
https://github.com/AdguardTeam/AdguardFilters/blob/32ed0d5ebce26a82e98de76186c64c07fff89a2c/SpywareFilter/sections/cookies.txt#L407
![image](https://user-images.githubusercontent.com/66902050/147844104-f591572d-b672-432e-9a27-a54f7105774a.png)
![image](https://user-images.githubusercontent.com/66902050/147844121-57c41429-ea81-4ac0-9406-768b2de6b50b.png)

2022-01-01 07:30 UTC, shenzhiming88 commented
@gorhill How about adding a `$cookie` parameter, like AdGuard does? If there are many general rules for removing cookies (like this one), or a list of cookies that specifically remove privacy-related cookies (e.g. https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/cookies.txt, which is part of the AdGuard privacy list), I don't think it's a wise choice to insert a script - it's not convenient to see the filter logs. When cookies are intercepted with this parameter, they can be marked red.
Thanks!

2022-01-01 12:09 UTC, gwarser commented
Does not work because it's http-only cookie

![image](https://user-images.githubusercontent.com/886325/147850215-8c7d6321-ddab-40f2-b90e-77416de402cf.png)

2022-01-01 12:11 UTC, gwarser commented
AdGuard doc about `$cookie` https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#cookie-modifier

2022-01-01 12:44 UTC, shenzhiming88 commented
@gwarser Okay, I'll try it now and see if AdGuard can intercept it.

2022-01-01 13:11 UTC, gorhill commented
> how the user uses the site

A site can know how it is being used by merely analyzing the fetching of resources from that site. Not that I am against supporting a new `cookie` modifier, but I really need to be convinced this really accomplishes something of value rather than just be a feature checkbox.

2022-01-01 13:14 UTC, shenzhiming88 commented
> > how the user uses the site
> 
> A site can know how it is being used by merely analyzing the fetching of resources from that site -- no cookies needed. Not that I am against supporting a new `cookie` modifier, but I really need to be convinced this really accomplishes something of value rather than just be a feature checkbox.

I'm sorry I don't know much about this. But I think you can check the AdGuard privacy list for cookies - https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/cookies.txt, the comments in the list seems to indicate that some cookies are related to tracking

2022-01-02 23:10 UTC, krystian3w commented
`$cookie` also block few Russian 🇷🇺  ads, may help reduce use `.user.js` for `dimisa ru-adlist`.

2022-01-02 23:16 UTC, krystian3w requested changes
<!-- -->

2022-01-05 06:47 UTC, closed without merging