[Annoyance] Chinese webpage folded content
uBlockOrigin/uAssets pull request #9989
Opened 2021-09-13 15:14 UTC by shenzhiming88

Some Chinese pages collapse their content and when clicking on the "expand all content" widget, an annoying self-promotional message pops up recommending that the user open the app to continue reading (not mandatory).
Therefore, these rules automatically expand all the content of the article, avoiding those annoying self-promotions
Test address (using mobile UA) :
`https://blog.csdn.net/qq_33611327/article/details/104499375`
`https://www.jianshu.com/p/70208fbc8e43`
![Screenshot_2021-09-13-23-02-52-653_org mozilla firefox](https://user-images.githubusercontent.com/66902050/133109512-39d7b42a-02b2-4497-8817-b567a36ac96a.jpg)
![Screenshot_2021-09-13-23-03-10-966_org mozilla firefox](https://user-images.githubusercontent.com/66902050/133110032-13cc7fc6-5e46-454c-a75e-a52a663bcf2d.jpg)
Refence: https://github.com/AdguardTeam/AdguardFilters/pull/89571

2021-09-13 21:18 UTC, Stateofminf commented
Att. Eml #9968 `#[i](https://github.com/AdguardTeam/AdguardFilters/pull/89571) ``

2021-09-13 21:19 UTC, Stateofminf commented
> Some Chinese pages collapse their content and when clicking on the "expand all content" widget, an annoying self-promotional message pops up recommending that the user open the app to continue reading (not mandatory).
> Therefore, these rules automatically expand all the content of the article, avoiding those annoying self-promotions
> Test address (using mobile UA) :
> `https://blog.csdn.net/qq_33611327/article/details/104499375`
> `https://www.jianshu.com/p/70208fbc8e43`
> ![Screenshot_2021-09-13-23-02-52-653_org mozilla firefox](https://user-images.githubusercontent.com/66902050/133109512-39d7b42a-02b2-4497-8817-b567a36ac96a.jpg)
> ![Screenshot_2021-09-13-23-03-10-966_org mozilla firefox](https://user-images.githubusercontent.com/66902050/133110032-13cc7fc6-5e46-454c-a75e-a52a663bcf2d.jpg)
> Refence: [AdguardTeam/AdguardFilters#89571](https://github.com/AdguardTeam/AdguardFilters/pull/89571)

Blob

2021-09-13 21:21 UTC, Stateofminf requested changes
Cybersecurity 1080
Kapersky not McAfee
#``

2021-09-14 08:41 UTC, closed without merging

2021-09-14 15:12 UTC, shenzhiming88 commented
@uBlock-user Hello! This site is having the same problem. In addition to that, ads are appearing on that page. Please deal with it, thanks!
`https://jingyan.baidu.com/article/63f23628ea2a484309ab3d6d.html`
![Screenshot_2021-09-14-23-08-17-612_org mozilla firefox](https://user-images.githubusercontent.com/66902050/133283696-929d653f-1d47-484a-bca6-fd2440768cc2.jpg)
![IMG_20210914_230906](https://user-images.githubusercontent.com/66902050/133283950-ba519bae-a801-4abf-8850-fc23d14ea163.jpg)

2021-09-14 21:48 UTC, uBlock-user commented
> In addition to that, ads are appearing on that page. Please deal with it, thanks!

Did you report ads to Chinese list ? 

I can't open the site due to site certificate issue

2021-09-15 14:27 UTC, shenzhiming88 commented
> 
> Did you report ads to Chinese list ?

Hello, I will provide feedback later. I would like you to take care of the content folding issue first, thanks!

> 
> I can't open the site due to site certificate issue

I don't know why, but I was able to open it normally. Maybe you can try to connect using VPN